name: twitter
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  redstone: any
  redstone_web_socket: any
dev_dependencies:
  crypto: '>=0.9.0 <0.10.0'
  json_object: '>=1.0.18+2 <2.0.0'
  unittest: any
